### ISSUE TITLE
Update Pixlet to 0.28.4

### ISSUE THREAD

**Issue by avidNewb** [btjones/axilla#27]
Certain community scripts don't work with this version.  Would it be possible to upgrade pixlet?

**Comment by btjones** [comment]
I tried to update to the latest Pixlet version but am running into an error. I think it may be because Netlify deprecated the Ubuntu deploy image I was previously using and the new version may not be playing nicely with some of the libraries Pixlet needs to execute. I'll take another look at some point (though not sure when).

**Comment by avidNewb** [comment]
> I tried to update to the latest Pixlet version but am running into an error. I think it may be because Netlify deprecated the Ubuntu deploy image I was previous using and the new version may not be playing nicely with some of the libraries Pixlet needs to execute. I'll take another look at some point (though not sure when).

You're pretty awesome for trying.  This would be just what I need for a project I'm working on.

**Comment by avidNewb** [comment]
I've been trying to deploy a fork or your repo.  functions folder doesn't fully upload for some reason.  The only files inside in the netlify instance are axilla.js and the assets folder.  If I copy the lib and pixlet folder to the assets folder then they get uploaded.  I can then change the path to reflect this move and instead of a "spawn ENOENT" error, I get a "spawn EACCES" error.  I'm not sure how to configure what folders get uploaded and what permissions they have.

**Comment by avidNewb** [comment]
Ok.  I'm a step closer by adding and "included files" section to the functions section in the netlify.toml.  Now it's got all of the files but fails looking for libweb.so.6 instead of libweb.so.7.  I'm sure this has to do with how I compiled.

**Comment by btjones** [comment]
It's been a while since I dug into all of the library related stuff, and this may not work, BUT what if you try renaming libweb.so.7 to libweb.so.6? I think I may have done something like that before and it just worked. Definitely not the best approach but it could get it running.

**Comment by avidNewb** [comment]
So I recompiled with the right libwebp library and I don't think that will be an issue.  I keep running into the "spawn functions/axilla/pixlet/pixlet-aws EACCES" error though and I don't understand how I got past it several times

**Comment by avidNewb** [comment]
Lol one step at a time.  Now I can't read the output file.  Getting closer

**Comment by avidNewb** [comment]
I did it.  I don't really know what I did but it runs.  When I get a chance to clean up, I'll do a pull request for what I have. [avidMatrix](https://avidmatrix.netlify.com)

**Comment by avidNewb** [comment]
I'm gonna submit a pull request as soon as I can retest.  Just a heads up, the EACCES error I mentioned before is something that shows up every time I publish and goes away within an hour.  Usually about 20 minutes.  I have no idea why but it caused me a headache until I realized it resolved itself.

**Comment by btjones** [comment]
Nice work, and thank you! I had to jump through so many hoops to get things working on Netlify when I originally built this so I feel your pain of figuring it out with their recent changes. All 66 commits of it, ha! I'm going to go ahead and merge your PR and then create a follow on PR to clean up a few things (linting errors, docs, etc).

I'm really curious what you had to do to get Pixlet compiling for Netlify / Ubuntu 20.04 so that I can get it building again myself. Could you share any details? Thanks!

**Comment by btjones** [comment]
> Just a heads up, the EACCES error I mentioned before is something that shows up every time I publish and goes away within an hour. Usually about 20 minutes.

I'm seeing this too - really weird. Since it resolves eventually it must be a Netlify issue.

**Comment by btjones** [comment]
Posted a question about the EACCES error on the Netlify forums: https://answers.netlify.com/t/netlify-functions-child-process-execfile-temporary-eacces-error/103789
